spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suptea?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: yourpass
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  mybatis.type-aliases-package: com.markerhub.entity
server:
  port: 8082
supportTeach:
  jwt:
    secret: f4654520343asdde581c0fdasdfgher
    expire: 604800
    header: Authorization